name: my_simple_store
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.1
  floating_action_bubble: ^1.1.4
  sqflite: ^2.2.4+1
  path_provider: ^2.0.12
  sliding_up_panel: ^2.0.0+1
  flutter_zoom_drawer: ^3.0.3
  intl: ^0.18.0
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

 
  assets:
    - assets/images/
    - assets/icons/
    - fonts/
  

  
  # fonts:
  #   - family: DancingScript
  #     fonts:
  #       - asset: fonts/Dancing/DancingScript-Bold.ttf
  #       - asset: fonts/Dancing/DancingScript-Medium.ttf
  #       - asset: fonts/Dancing/DancingScript-Regular.ttf
  #       - asset: fonts/Dancing/DancingScript-SemiBold.ttf
     
