name: my_simple_store
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  floating_action_bubble: ^1.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.6.1
  flutter_slidable: ^2.0.0
  flutter_svg: ^2.0.5
  flutter_zoom_drawer: ^3.0.3
  get_it: ^7.4.1
  http: ^0.13.6
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  path_provider: ^2.0.12
  pinput: ^2.2.31
  sliding_up_panel: ^2.0.0+1
  sqflite: ^2.2.4+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - fonts/

# fonts:
#   - family: DancingScript
#     fonts:
#       - asset: fonts/Dancing/DancingScript-Bold.ttf
#       - asset: fonts/Dancing/DancingScript-Medium.ttf
#       - asset: fonts/Dancing/DancingScript-Regular.ttf
#       - asset: fonts/Dancing/DancingScript-SemiBold.ttf
